---
new_page_extension: html
auto_deploy: false
admin_path: "/.forestry"
webhook_url: 
sections:
- type: document
  path: ".forestry/settings.yml"
  label: Global site config
- type: directory
  path: ''
  label: home
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - 'INCOMING_HOOK_BODY= '
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
